<a href="https://colab.research.google.com/github/x1Sensei/x1Sensei/blob/main/practiceIA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!python --version

Python 3.10.12


tiposDeDatosBasicos

In [ ]:
sample1=10
sample2=2.2
sample3="Jimmy"

print(type(sample1))
print(type (sample2))
print(type (sample3))

print(sample1+sample2)
print(sample1+sample2)
print(sample1**2)

s1=True
s2=False

#print(s1 and s2)
#print(s1 or s2)
#print(not s1)
#print(len(sample3))
#print(sample3.upper())
#print(sample3.lower())
#print(sample3.capitalize())



<class 'int'>
<class 'float'>
<class 'str'>
12.2
12.2
100


print=imprimir -----type= función que pertenece a una clase que a su vez es una librería de python tipo de dato, es método---- potencia *** ---datos booleanos true ---- operaciones logicas and y or

In [ ]:
someList= list()
someList=["samsumg", "Huawei", "xiaomi", "iphone", "Nokia", True, False]
print(someList[6] )
print(len(someList))

#print("---------------------------------")

#for i in someList:
 # print(i)

#someList.append("regla")
#print("--------------------------------------")
#for i in someList:
 # print(i)
  #someList.pop(2)
#print("************")
#for i in someList:
 # print(i)

#print("---------")
#print(someList[1:4])

print(someList[-1])
print(someList[:3])



False
7
False
['samsumg', 'Huawei', 'xiaomi']


In [ ]:
d={"name":"Jimmy", "Edad": 20, "ciudad": "Santo Domingo"}

#print(d["name"])
#print(d["ciudad"])

#d["uni"]="Uleam"
#print(d["uni"])


for key in d:
  print(d[key])

Jimmy
20
Santo Domingo


In [ ]:
listTemp=list()
listTemp.append(-1)
listTemp.append(0)
listTemp.append(1)
print(listTemp)

print("My list: {}".format(listTemp))

def positiveNegative(number):
  if number<0:
    print("Negative")
  elif number>0:
    print("Positive")
  else:
    print("Zero")


pass

for item in listTemp:
  positiveNegative(item)


#number=listTemp[1]
#print("which: " ,number)
#positiveNegative(number)

[-1, 0, 1]
which:  0
Zero


In [2]:
class persons():
  def __init__ (self, name, age):
    self.name=name
    self.age=age


  def message(self):
    print("hello, {}".format(self.name))
    print("Your age is, {}".format(self.age))

person1=persons("Jorge", 12)
person2=persons("Bryan", 15)
person3=persons("Maria", 16)
person4=persons("Lucas", 18)


person1.message()




hello, Jorge
Your age is, 12


In [4]:
import numpy as jimmy

a=jimmy.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0]=5
print(a)

print("*********************")
b=jimmy.array([[1,2,3],[1,3,5]])
print(type(b))
print(b.shape)
print(b)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
*********************
<class 'numpy.ndarray'>
(2, 3)
[[1 2 3]
 [1 3 5]]


In [ ]:
import numpy as Ale
a=Ale.array([1,2,3])
print(a)
print(a.shape)
print(type(a))



import numpy as np

b=np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b)
print("number 5 : " ,b[1,1])

print("----------")
c=np.zeros((3,4), dtype=float)
print(c)
# numpy.zeros => crea una matriz con ceros(0)

c=np.ones((3,4), dtype=float)
print("----------")
print(c)
# numpy.ones => crea una matriz con unos(1)

print("----------")
c=np.eye(5)

print(c)
# numpy.eye => crea una matriz identidad


In [12]:
d=10*np.random.randn(4,4)
print(d)

[[ -8.15167978  -6.51762446   9.29422109  -1.95651787]
 [ -1.37875537  15.75620123  -8.89455913   4.06269494]
 [ -3.09891414  20.96886193   0.89938211  10.85973297]
 [-10.92626039  13.72816283   5.92216678 -10.54426022]]


In [14]:
print(d[2,2])
tmp=np.array(d)
tmp[2,2]=150
print(tmp[2,2])


0.8993821109233744
150.0


In [15]:
d=10*np.random.randn(5,5)
print(d)

[[  1.79971445  10.22886534   3.18243283  14.86450497  -3.63623663]
 [  7.13201417 -14.51742925  -5.26646618   4.39923178 -22.44997716]
 [-11.72596815   6.27841775   0.67383823   7.43249675  -1.24718932]
 [ -0.81463002   9.81940136  -5.6518585    7.48561069  -5.20273193]
 [  4.26725319  18.31646449  -9.47988047   0.36440315  16.08465865]]


In [17]:
tmp=np.array(d[1:4,1:4])
print(tmp)
print(tmp.shape)

[[-14.51742925  -5.26646618   4.39923178]
 [  6.27841775   0.67383823   7.43249675]
 [  9.81940136  -5.6518585    7.48561069]]
(3, 3)


In [18]:
tmp=np.array(d[:,1:4])
print(tmp)
print(tmp.shape)

[[ 10.22886534   3.18243283  14.86450497]
 [-14.51742925  -5.26646618   4.39923178]
 [  6.27841775   0.67383823   7.43249675]
 [  9.81940136  -5.6518585    7.48561069]
 [ 18.31646449  -9.47988047   0.36440315]]
(5, 3)


In [ ]:
mask=d>10.0
print(d.shape)
print(mask)
print(type(mask))

tmp=d[mask]
print("Values: {}".format(tmp))
print(type(tmp))
print(tmp.shape)

print(tmp[1])

In [31]:
a=10*np.random.randn(3,3)
b=10*np.random.randn(3,3)
print(a)
print("------------------------------------------")
print("------------------------------------------")
print(b)


[[  6.34656958  12.41517316   3.37915167]
 [-19.44352075 -24.11308524   7.27739716]
 [  1.73892267  -3.23972787  10.89831346]]
------------------------------------------
------------------------------------------
[[  7.8819034   -4.01275956 -21.69584736]
 [ 19.69204943 -10.98614977  -2.31307294]
 [  8.95878555  26.41982039  -3.18607626]]


In [32]:
print(a+b)

[[ 14.22847298   8.4024136  -18.31669569]
 [  0.24852868 -35.09923501   4.96432422]
 [ 10.69770822  23.18009253   7.71223719]]


In [33]:
print(a-b)

[[ -1.53533382  16.42793272  25.07499903]
 [-39.13557018 -13.12693547   9.5904701 ]
 [ -7.21986288 -29.65954826  14.08438972]]


In [34]:
print(a*b)

[[  50.02304832  -49.81910476  -73.31355892]
 [-382.88277162  264.90996592  -16.83315044]
 [  15.57863532  -85.59302832  -34.72285781]]


In [36]:
print(np.add(a,b))

[[ 14.22847298   8.4024136  -18.31669569]
 [  0.24852868 -35.09923501   4.96432422]
 [ 10.69770822  23.18009253   7.71223719]]


In [48]:
c=np.array([[2,1],[3,3]])
print(c.shape)

print(c)

print("-------")

print(np.square(c))  #elevar al cuadrado
print("------------")
print(np.power(c,3)) #elevar al cubo

(2, 2)
[[2 1]
 [3 3]]
-------
[[4 1]
 [9 9]]
------------
[[ 8  1]
 [27 27]]


In [51]:
c=10*np.random.randn(3,4)
print(c)

[[ -5.69623615  -1.39856075 -11.49381303  -2.84192903]
 [ 11.7380982    1.33545327  14.785994     0.08854601]
 [ -2.46891049  -8.29868999   0.73159613 -16.36372792]]


In [55]:
c=10*np.random.randn(3,3)
c=10*np.random.randn(3,3)
print(c)
print()
print(b)

[[ -8.37368986  -7.35626017  -1.16519913]
 [-19.83006507 -10.0367619   -9.67509712]
 [ -2.95948944   1.18023031   2.25041611]]

[[  7.8819034   -4.01275956 -21.69584736]
 [ 19.69204943 -10.98614977  -2.31307294]
 [  8.95878555  26.41982039  -3.18607626]]


In [ ]:
y1=np.vstack((c,b))
print(y1)
y1=np.hstack((c,b))
print(y1)